<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>easyLib.Debug</RootNamespace>
		<AssemblyVersion>2.0.0.0</AssemblyVersion>
		<FileVersion>$(AssemblyVersion)</FileVersion>
		<Authors>chez.adel@outlook.fr</Authors>
		<Copyright>chez.adel@outlook.fr (c) 2014 - 2025</Copyright>
	</PropertyGroup>

</Project>
